import { RecoveryCase } from "@/lib/api";

const base = {
  state: "DIAGNOSED",
  currency: "INR",
  created_at: "2026-09-01T04:42:00Z",
};

export const demoCases: RecoveryCase[] = [
  { ...base, id: "demo-northstar", customer_name: "Northstar Labs", customer_segment: "B2B account", source_type: "Overdue B2B invoice", provider_reference: "inv_Q7N4K8", risk_amount_minor: 799900, natural_recovery_score: .18, recovery_priority: "CRITICAL", recommended_action: "VOICE_AGENT", next_step: "Confirm payment date with finance owner", diagnosis: { failure_class: "INVOICE_OVERDUE", confidence: .91, evidence: ["Invoice overdue by 14 days", "Two previous reminders opened"] } },
  { ...base, id: "demo-vikram", customer_name: "Vikram Shah", customer_segment: "SaaS subscription", source_type: "Failed subscription", provider_reference: "sub_Q2K9D3", risk_amount_minor: 249900, natural_recovery_score: .08, recovery_priority: "HIGH", recommended_action: "UPDATE_PAYMENT_METHOD", next_step: "Email a secure card-update link", diagnosis: { failure_class: "CARD_EXPIRED", confidence: .96, evidence: ["Razorpay error_reason=expired_card"] } },
  { ...base, id: "demo-ananya", customer_name: "Ananya Bose", customer_segment: "Insurance mandate", source_type: "Mandate failure", provider_reference: "sub_Q5M1P6", risk_amount_minor: 329900, natural_recovery_score: .08, recovery_priority: "HIGH", recommended_action: "UPDATE_PAYMENT_METHOD", next_step: "Request mandate re-authorisation", diagnosis: { failure_class: "MANDATE_INVALID", confidence: .93, evidence: ["Mandate authentication is no longer valid"] } },
  { ...base, id: "demo-kavya", customer_name: "Kavya Rao", customer_segment: "Membership", source_type: "Failed subscription", provider_reference: "sub_Q8B4T2", risk_amount_minor: 99900, natural_recovery_score: .45, recovery_priority: "MEDIUM", recommended_action: "NUDGE", next_step: "Send a low-cost SMS after salary-day signal", diagnosis: { failure_class: "INSUFFICIENT_FUNDS", confidence: .88, evidence: ["Razorpay error_reason=insufficient_funds"] } },
  { ...base, id: "demo-paperplane", customer_name: "Paperplane Studio", customer_segment: "B2B account", source_type: "Overdue B2B invoice", provider_reference: "inv_Q1C7W9", risk_amount_minor: 949900, natural_recovery_score: .18, recovery_priority: "CRITICAL", recommended_action: "PAYMENT_LINK", next_step: "Email invoice summary and payment link", diagnosis: { failure_class: "INVOICE_OVERDUE", confidence: .86, evidence: ["Invoice overdue by 9 days"] } },
  { ...base, id: "demo-aarav", customer_name: "Aarav Mehta", customer_segment: "SaaS subscription", source_type: "Failed subscription", provider_reference: "sub_Q4J2L8", risk_amount_minor: 149900, natural_recovery_score: .60, recovery_priority: "LOW", recommended_action: "NATIVE_RETRY_WAIT", next_step: "Wait for Razorpay native retry", diagnosis: { failure_class: "TECHNICAL_FAILURE", confidence: .72, evidence: ["First observed failure", "12 successful renewals"] } },
  { ...base, id: "demo-meera", customer_name: "Meera Nair", customer_segment: "SaaS subscription", source_type: "Failed subscription", provider_reference: "sub_Q9F6R3", risk_amount_minor: 189900, natural_recovery_score: .08, recovery_priority: "HIGH", recommended_action: "PAYMENT_LINK", next_step: "Send a personalised Razorpay Payment Link", diagnosis: { failure_class: "BANK_DECLINED", confidence: .89, evidence: ["Razorpay error_reason=bank_declined"] } },
  { ...base, id: "demo-sana", customer_name: "Sana Khan", customer_segment: "Consumer plan", source_type: "Failed subscription", provider_reference: "sub_Q3H8A5", risk_amount_minor: 119900, natural_recovery_score: .45, recovery_priority: "MEDIUM", recommended_action: "NUDGE", next_step: "Send one WhatsApp reminder, then wait", diagnosis: { failure_class: "INSUFFICIENT_FUNDS", confidence: .86, evidence: ["Razorpay error_reason=low_balance"] } },
];
