from enum import StrEnum


class CaseState(StrEnum):
    AT_RISK = "AT_RISK"
    DIAGNOSED = "DIAGNOSED"
    PLANNED = "PLANNED"
    WAITING = "WAITING"
    ACTION_SCHEDULED = "ACTION_SCHEDULED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    OBSERVING = "OBSERVING"
    RECOVERED_VERIFIED = "RECOVERED_VERIFIED"
    REPLAN = "REPLAN"
    STOPPED = "STOPPED"
    EXHAUSTED = "EXHAUSTED"


class ActionType(StrEnum):
    WAIT = "WAIT"
    NATIVE_RETRY_WAIT = "NATIVE_RETRY_WAIT"
    NUDGE = "NUDGE"
    UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD"
    PAYMENT_LINK = "PAYMENT_LINK"
    VOICE_AGENT = "VOICE_AGENT"
    HUMAN_ESCALATE = "HUMAN_ESCALATE"
    STOP = "STOP"


class PolicyVerdict(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    DEFER = "DEFER"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"


class ActionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    SCHEDULED = "SCHEDULED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"
