"""initial schema

Revision ID: 37b96b5b6c8b
Revises:
Create Date: 2026-09-01 01:42:06.093432
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "37b96b5b6c8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("customer_count", sa.Integer(), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("code_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("artifact_paths", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbox_pending", "outbox_events", ["dispatched_at", "available_at"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=60), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_kind", sa.String(length=100), nullable=False),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("decision", sa.JSON(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_aggregate",
        "audit_events",
        ["aggregate_type", "aggregate_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_merchant_id"), "audit_events", ["merchant_id"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("provider_customer_id", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("email_masked", sa.String(length=200), nullable=True),
        sa.Column("phone_masked", sa.String(length=50), nullable=True),
        sa.Column("contact_preferences", sa.JSON(), nullable=False),
        sa.Column("consent", sa.JSON(), nullable=False),
        sa.Column("opted_out", sa.Boolean(), nullable=False),
        sa.Column("contacts_24h", sa.Integer(), nullable=False),
        sa.Column("contacts_7d", sa.Integer(), nullable=False),
        sa.Column("promise_to_pay_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "provider_customer_id"),
    )
    op.create_index(op.f("ix_customers_merchant_id"), "customers", ["merchant_id"], unique=False)
    op.create_table(
        "evaluation_case_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=False),
        sa.Column("synthetic_customer_id", sa.String(length=100), nullable=False),
        sa.Column("strategy", sa.String(length=40), nullable=False),
        sa.Column("cohort", sa.String(length=60), nullable=False),
        sa.Column("action_type", sa.String(length=60), nullable=False),
        sa.Column("recovered", sa.Boolean(), nullable=False),
        sa.Column("recovered_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("contacts", sa.Integer(), nullable=False),
        sa.Column("spend_minor", sa.BigInteger(), nullable=False),
        sa.Column("time_to_recover_hours", sa.Float(), nullable=True),
        sa.Column("policy_violation", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["evaluation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_run_id", "synthetic_customer_id", "strategy"),
    )
    op.create_index(
        op.f("ix_evaluation_case_results_evaluation_run_id"),
        "evaluation_case_results",
        ["evaluation_run_id"],
        unique=False,
    )
    op.create_table(
        "merchant_policy_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("rules_json", sa.JSON(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "version"),
    )
    op.create_index(
        op.f("ix_merchant_policy_versions_merchant_id"),
        "merchant_policy_versions",
        ["merchant_id"],
        unique=False,
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("raw_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "provider_event_id"),
    )
    op.create_index(
        op.f("ix_webhook_events_event_type"), "webhook_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_events_merchant_id"), "webhook_events", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_webhook_unprocessed", "webhook_events", ["processed_at", "received_at"], unique=False
    )
    op.create_table(
        "recovery_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("budget_minor", sa.BigInteger(), nullable=False),
        sa.Column("contact_budget", sa.Integer(), nullable=False),
        sa.Column("reserved_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("reserved_contacts", sa.Integer(), nullable=False),
        sa.Column("estimated_incremental_minor", sa.BigInteger(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["merchant_policy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recovery_runs_merchant_id"), "recovery_runs", ["merchant_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("razorpay_subscription_id", sa.String(length=100), nullable=False),
        sa.Column("razorpay_plan_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("next_charge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "razorpay_subscription_id"),
    )
    op.create_index(
        op.f("ix_subscriptions_customer_id"), "subscriptions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_merchant_id"), "subscriptions", ["merchant_id"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_table(
        "payment_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("webhook_event_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=100), nullable=True),
        sa.Column("provider_invoice_id", sa.String(length=100), nullable=True),
        sa.Column("event_kind", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_description", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["webhook_event_id"],
            ["webhook_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "provider_payment_id", "event_kind"),
    )
    op.create_index(
        op.f("ix_payment_events_merchant_id"), "payment_events", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_events_subscription_id"),
        "payment_events",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "recovery_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("episode_key", sa.String(length=240), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("risk_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("diagnosis", sa.JSON(), nullable=False),
        sa.Column("natural_recovery_score", sa.Float(), nullable=False),
        sa.Column("contact_count", sa.Integer(), nullable=False),
        sa.Column("replan_count", sa.Integer(), nullable=False),
        sa.Column("terminal_reason", sa.String(length=100), nullable=True),
        sa.Column("recovered_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "episode_key"),
    )
    op.create_index(
        "ix_case_state_created", "recovery_cases", ["state", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_cases_customer_id"), "recovery_cases", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_cases_merchant_id"), "recovery_cases", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_cases_subscription_id"),
        "recovery_cases",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "candidate_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=60), nullable=False),
        sa.Column("probability_action", sa.Float(), nullable=False),
        sa.Column("probability_natural", sa.Float(), nullable=False),
        sa.Column("action_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("fatigue_penalty_minor", sa.BigInteger(), nullable=False),
        sa.Column("risk_penalty_minor", sa.BigInteger(), nullable=False),
        sa.Column("eirv_minor", sa.BigInteger(), nullable=False),
        sa.Column("contact_units", sa.Integer(), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("policy_verdict", sa.String(length=40), nullable=False),
        sa.Column("policy_reasons", sa.JSON(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recovery_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "case_id", "action_type"),
    )
    op.create_index(
        op.f("ix_candidate_actions_case_id"), "candidate_actions", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_actions_run_id"), "candidate_actions", ["run_id"], unique=False
    )
    op.create_table(
        "conversation_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("content_redacted", sa.Text(), nullable=False),
        sa.Column("extracted", sa.JSON(), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_events_case_id"), "conversation_events", ["case_id"], unique=False
    )
    op.create_table(
        "recovery_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_action_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("provider_reference", sa.String(length=100), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("contact_units", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_action_id"],
            ["candidate_actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recovery_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("provider_reference"),
    )
    op.create_index(
        op.f("ix_recovery_actions_case_id"), "recovery_actions", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_actions_run_id"), "recovery_actions", ["run_id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=200), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["recovery_actions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_action_id"), "approvals", ["action_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_action_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_recovery_actions_run_id"), table_name="recovery_actions")
    op.drop_index(op.f("ix_recovery_actions_case_id"), table_name="recovery_actions")
    op.drop_table("recovery_actions")
    op.drop_index(op.f("ix_conversation_events_case_id"), table_name="conversation_events")
    op.drop_table("conversation_events")
    op.drop_index(op.f("ix_candidate_actions_run_id"), table_name="candidate_actions")
    op.drop_index(op.f("ix_candidate_actions_case_id"), table_name="candidate_actions")
    op.drop_table("candidate_actions")
    op.drop_index(op.f("ix_recovery_cases_subscription_id"), table_name="recovery_cases")
    op.drop_index(op.f("ix_recovery_cases_merchant_id"), table_name="recovery_cases")
    op.drop_index(op.f("ix_recovery_cases_customer_id"), table_name="recovery_cases")
    op.drop_index("ix_case_state_created", table_name="recovery_cases")
    op.drop_table("recovery_cases")
    op.drop_index(op.f("ix_payment_events_subscription_id"), table_name="payment_events")
    op.drop_index(op.f("ix_payment_events_merchant_id"), table_name="payment_events")
    op.drop_table("payment_events")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_merchant_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_customer_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_recovery_runs_merchant_id"), table_name="recovery_runs")
    op.drop_table("recovery_runs")
    op.drop_index("ix_webhook_unprocessed", table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_merchant_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_type"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(
        op.f("ix_merchant_policy_versions_merchant_id"), table_name="merchant_policy_versions"
    )
    op.drop_table("merchant_policy_versions")
    op.drop_index(
        op.f("ix_evaluation_case_results_evaluation_run_id"), table_name="evaluation_case_results"
    )
    op.drop_table("evaluation_case_results")
    op.drop_index(op.f("ix_customers_merchant_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_audit_events_merchant_id"), table_name="audit_events")
    op.drop_index("ix_audit_aggregate", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_outbox_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("merchants")
    op.drop_table("evaluation_runs")
    # ### end Alembic commands ###
